[package]
name = "calf"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/puffyCid/calf"
description = "A very basic library to read QCOW files"
keywords = ["forensics"]

[dependencies]
nom = "8.0.0"
log = "0.4.29"
base64 = "0.22.1"
ext4-fs = "0.1.2"
